# Generated by Django 6.0.3 on 2026-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_locked_until',
            new_name='locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='If True user must verify OTP after password login'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_expiry',
            field=models.DateTimeField(blank=True, help_text='When the current email OTP expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='Current email OTP code (cleared after use)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_type',
            field=models.CharField(choices=[('EMAIL', 'Email OTP'), ('TOTP', 'Authenticator App')], default='EMAIL', help_text='Which MFA method the user has enabled', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_confirmed',
            field=models.BooleanField(default=False, help_text='True after user scans QR code and verifies first code'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Secret key shared with the authenticator app', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer'), ('TRAVEL_AGENT', 'Travel Agent')], default='CUSTOMER', max_length=20),
        ),
    ]
