# Generated by Django 6.0.3 on 2026-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer'), ('TRAVEL_AGENT', 'Travel Agent'), ('MANAGER', 'Manager')], default='CUSTOMER', max_length=20),
        ),
    ]
