# Generated by Django 6.0.3 on 2026-04-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL to listing image', max_length=500, null=True),
        ),
    ]
