# Generated by Django 6.0.3 on 2026-04-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL to listing image — paste any photo link here', max_length=500, null=True),
        ),
    ]
