# Generated by Django 6.0.3 on 2026-04-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='agoda_url',
            field=models.URLField(blank=True, help_text='Paste exact Agoda URL for this listing', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='booking_com_url',
            field=models.URLField(blank=True, help_text='Paste exact Booking.com URL for this listing', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='expedia_url',
            field=models.URLField(blank=True, help_text='Paste exact Expedia URL for this listing', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='skyscanner_url',
            field=models.URLField(blank=True, help_text='Paste exact Skyscanner URL for this flight', max_length=500, null=True),
        ),
    ]
