# Generated by Django 6.0.3 on 2026-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_agoda_url_listing_booking_com_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='agoda_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Agoda (for comparison)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='booking_com_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Booking.com (for comparison)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='expedia_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Expedia (for comparison)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='skyscanner_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Skyscanner (for comparison)', max_digits=10, null=True),
        ),
    ]
