# Generated by Django 6.0.5 on 2026-05-18 12:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_rejection_reason_alter_listing_agoda_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='agoda_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Agoda (for comparison table)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='agoda_url',
            field=models.URLField(blank=True, help_text='Paste exact Agoda URL for this listing', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_seats',
            field=models.IntegerField(default=0, help_text='Number of seats still available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='booking_com_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Booking.com (for comparison table)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='booking_com_url',
            field=models.URLField(blank=True, help_text='Paste exact Booking.com URL for this listing', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, help_text='Main city of destination', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(help_text='Country of destination', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Full description shown to customers'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='destination',
            field=models.CharField(help_text='Destination name (e.g. Bali)', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='duration_days',
            field=models.IntegerField(default=1, help_text='Total duration in days', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateField(help_text='Trip end / check-out date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='expedia_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Expedia (for comparison table)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='expedia_url',
            field=models.URLField(blank=True, help_text='Paste exact Expedia URL for this listing', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_seats',
            field=models.IntegerField(default=0, help_text='Maximum total seats for this listing', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin',
            field=models.CharField(help_text='Departure city (e.g. Sydney)', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, help_text='Original price per person in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average customer rating out of 5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason given if listing was rejected by Manager'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='skyscanner_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price shown on Skyscanner (for comparison table)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='skyscanner_url',
            field=models.URLField(blank=True, help_text='Paste exact Skyscanner URL for this listing', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateField(help_text='Trip start / check-in date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLDOUT', 'Sold Out'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Eye-catching title for the listing', max_length=200),
        ),
        migrations.AlterModelTable(
            name='listing',
            table=None,
        ),
    ]
